import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

/** Matches `global.css` — hex/rgba so React Navigation and native views resolve colors reliably. */
export const THEME = {
	dark: {
		accent: '#22292b',
		accentForeground: '#f9fbfb',
		background: '#090b0c',
		border: 'rgba(255, 255, 255, 0.1)',
		card: '#161b1d',
		cardForeground: '#f9fbfb',
		chart1: '#7bf1a8',
		chart2: '#00c950',
		chart3: '#00a63e',
		chart4: '#008236',
		chart5: '#016630',
		destructive: '#ff6467',
		foreground: '#f9fbfb',
		input: 'rgba(255, 255, 255, 0.15)',
		muted: '#22292b',
		mutedForeground: '#9ca8ab',
		popover: '#161b1d',
		popoverForeground: '#f9fbfb',
		primary: '#005f5a',
		primaryForeground: '#f0fdfa',
		radius: '0.625rem',
		ring: '#67787c',
		secondary: '#27272a',
		secondaryForeground: '#fafafa',
	},
	light: {
		accent: '#f1f3f3',
		accentForeground: '#161b1d',
		background: '#ffffff',
		border: '#e3e7e8',
		card: '#ffffff',
		cardForeground: '#090b0c',
		chart1: '#7bf1a8',
		chart2: '#00c950',
		chart3: '#00a63e',
		chart4: '#008236',
		chart5: '#016630',
		destructive: '#e7000b',
		foreground: '#090b0c',
		input: '#e3e7e8',
		muted: '#f1f3f3',
		mutedForeground: '#67787c',
		popover: '#ffffff',
		popoverForeground: '#090b0c',
		primary: '#00786f',
		primaryForeground: '#f0fdfa',
		radius: '0.625rem',
		ring: '#9ca8ab',
		secondary: '#f4f4f5',
		secondaryForeground: '#18181b',
	},
};

export const NAV_THEME: Record<'dark' | 'light', Theme> = {
	dark: {
		...DarkTheme,
		colors: {
			background: THEME.dark.background,
			border: THEME.dark.border,
			card: THEME.dark.card,
			notification: THEME.dark.destructive,
			primary: THEME.dark.primary,
			text: THEME.dark.foreground,
		},
	},
	light: {
		...DefaultTheme,
		colors: {
			background: THEME.light.background,
			border: THEME.light.border,
			card: THEME.light.card,
			notification: THEME.light.destructive,
			primary: THEME.light.primary,
			text: THEME.light.foreground,
		},
	},
};
